version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"

    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
      - match:
          dependency_type: "development"
          update_type: "in_range"