name: Publish release

on:
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        # with:
        #   publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo outputs
        run: |
          echo "tag: ${{ steps.release-drafter.outputs.tag_name }}"
          echo "url: ${{ steps.release-drafter.outputs.html_url }}"
          echo "upload_url: ${{ steps.release-drafter.outputs.upload_url }}"
      
      # - uses: actions/checkout@v2
      # - run: |
      #     gh release upload ${{ steps.release-drafter.outputs.tag_name }} README.md
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
